baseurl = "https://sherrrwh.github.io"
languageCode = "en-us"
title = "Let's have some Soda"
theme = "retrofulhugo"
pygmentsUseClasses = true
#googleAnalytics = "XXX"
#disqusShortname = "XXX"

[Params]
  subtitle = ""
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  commit = false

[Author]
	handle = "norawww"
  name = "norawww"
  email = "sherlockwh@gmail.com"
  github = "sherrrwh"
  twitter = "your twitter handle"

[[menu.main]]
    name = "Menu Item"
    url = "http://google.com"
    weight = 1

#[[menu.main]]
#    name = "About"
#    url = "/page/about/"
#    weight = 2 
